# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20160918_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default=datetime.datetime(2016, 9, 19, 8, 16, 40, 80000, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
