# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20160919_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=250)),
                ('image_file', models.FileField(upload_to=b'')),
            ],
        ),
    ]
