# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
